### ISSUE TITLE
[graph] issue with feature visualizers transition

### ISSUE THREAD

**Issue by HarryLuUMN** [Visual-Intelligence-UMN/web-gnn-vis#133]
Feature visualizers from previous layer sometimes will disappear

![image](https://github.com/user-attachments/assets/52dd8247-c4d9-4dc8-94bb-672db30df455)

**Comment by HarryLuUMN** [comment]
Still has this error in the newest updates on dev branch

![Image](https://github.com/user-attachments/assets/91d3f27b-36bc-465a-be3b-4f02943447e3)

**Comment by mattx0601** [comment]
I fixed the issue already. My change was reverted in the dev branch for some strange reason. Will remerge my branch into dev in eta 3 hours.

**Comment by HarryLuUMN** [comment]
Thanks for updating!
