### ISSUE TITLE
[Matrix vis] minor bug found

### ISSUE THREAD

**Issue by chongwei729** [Visual-Intelligence-UMN/web-gnn-vis#147]
<img width="615" alt="Screenshot 2024-07-23 at 00 08 03" src="https://github.com/user-attachments/assets/b9933529-4f95-4464-a825-136ea0d6a0c0">

Steps to replicate:
1. click on one of the feature vectors
2. click to restore the view(precisely one time)

calculation animation components remain in the view

**Comment by HarryLuUMN** [comment]
Seems like the timer didn't clear correctly when recover the view

**Comment by HarryLuUMN** [comment]
Temp solution added
