### ISSUE TITLE
[graph] the hovering interaction with mini features and path opacity aren't sychronize

### ISSUE THREAD

**Issue by HarryLuUMN** [Visual-Intelligence-UMN/web-gnn-vis#150]
![image](https://github.com/user-attachments/assets/c684a242-9c05-4e03-add5-cbb51225a950)

**Comment by HarryLuUMN** [comment]
initial thought: the hovering interaction for mini features only apply to node label but not node body

**Comment by chongwei729** [comment]
the hovering interaction applies to both node labels and node body. When users move the mouse out of the node label, while still being inside the node body, it triggers the "mouseout" interaction for the node label and reduces the opacity of all node features to 0.
